### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by eeeple** [RaftLib/shm#1]
Hello,

I'm trying to build RaftLib on Windows using CMake and NMake/VS2015.3 as stated in the issue #7 filed under RaftLib but I'm facing problems while using NMake.
CMake completes without a problem, though, so that's a good start :)
Any ideas ?

Thanks !
[nmake_error_log.txt](https://github.com/RaftLib/shm/files/890513/nmake_error_log.txt)

**Comment by jonathan-beard** [comment]
Looks like issue #7 is closed and fixed in raftlib, I'm assuming it's fixed now here...seems to build for me in Windows.
