### ISSUE TITLE
Error: Main method not found in class StreamTest, please define the main method as:    public static void main(String[] args) or a JavaFX application class must extend javafx.application.Application

### ISSUE THREAD

**Issue by gmkafafi** [RaftLib/shm#3]
Hi! Thanks for the tutorial.
I wanted to integrate this into my program so I modified the StreamTest.java file a bit so that I could return a String (See Below) 

The issue is when I execute java -cp . StreamTest
I get Error: Main method not found in class StreamTest, please define the main method as:    public static void main(String[] args) or a JavaFX application class must extend javafx.application.Application

Any ideas on what I can do?

    import java.io.BufferedInputStream; 
    import java.io.IOException;
    import java.io.InputStream;

    public class StreamTest{
        private static final int buffer = 4096;
    
    public static String main(String [] args, String pass){
        InputStream is = null;
        BufferedInputStream bis = null;
        try{
            bis = new BufferedInputStream(System.in,buffer);
            StringBuilder sb = new StringBuilder();
            sb.append((char)bis.read());
            while(bis.available() > 0){
                sb.append((char)bis.read());
            }
            
            System.out.println("JAVA SIDE: "+sb.toString());
            pass=sb.toString();
            bis.close();
            return pass;
        }catch(IOException ex){
            
        }finally{
            
            
        }
		return pass;
        }
    }

**Comment by gmkafafi** [comment]
I've crossed posted this with more detail here: https://stackoverflow.com/questions/50600002/c-to-java-ipc-error-main-method-not-found-in-class-streamtest-please-define-th

**Comment by dogu-omer** [comment]
thanks
